---

AWSTemplateFormatVersion: '2010-09-09'

Description: Create a VPC

Parameters:
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    Description: IPv4 VPC CIDR (e.g. 172.16.24.0/21)
    Type: String

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-VPC"

Outputs:
  VPCID:
    Description: VpcId
    Value: !Ref VPC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ID"
